version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: exped_cluster_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: exped_cluster_db
    volumes:
      - exped_cluster_mysql_data:/var/lib/mysql
      - ./data/CASBotanybackup2024-08-19.sql.gz:/docker-entrypoint-initdb.d/CASBotanybackup2024-08-19.sql.gz
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: exped_cluster_phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_USER: myuser
      PMA_PASSWORD: mypassword
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  exped_cluster_mysql_data:
