services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: exped_cluster_mysql_container
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    command: >
      --max_allowed_packet=256M
      --net_buffer_length=16K
      --log-bin-trust-function-creators=ON
    volumes:
      - exped_cluster_mysql_data:/var/lib/mysql
      - ${SQL_DUMP_PATH}:/docker-entrypoint-initdb.d/cas-db.sql.gz
    ports:
      - "${MYSQL_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 10s
      retries: 5
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: exped_cluster_phpmyadmin_container
    env_file:
      - .env
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  exped_cluster_mysql_data:
